const data = {
    products:[
        {
            _id:'1',
            name:'Diamond Pickaxe',
            category: 'Pickaxe',
            image:'/images/minecraft_diamond_pickaxe.png',
            price:20,
            brand:'Diamond',
            rating:5,
            numReviews:13,
            description:'High quality diamond pickaxe. Full durability. Unenchanted.',
        },
        {
            _id:'2',
            name:'Diamond Sword',
            category: 'Sword',
            image:'/images/diamond_sword.png',
            price:18,
            brand:'Diamond',
            rating:5,
            numReviews:24,
            description:'High quality diamond sword. Full durability. Unenchanted.',
        },
        {
            _id:'3',
            name:'Diamond Axe',
            category: 'Axe',
            image:'/images/diamond_axe.png',
            price:14,
            brand:'Diamond',
            rating:5,
            numReviews:10,
            description:'High quality diamond axe. Full durability. Unenchanted.',
        },
        {
            _id:'4',
            name:'Diamond Shovel',
            category: 'Shovel',
            image:'/images/diamond_shovel.png',
            price:14,
            brand:'Diamond',
            rating:5,
            numReviews:8,
            description:'High quality diamond shovel. Full durability. Unenchanted.',
        },
        {
            _id:'5',
            name:'Diamond Hoe',
            category: 'Hoe',
            image:'/images/diamond_hoe.png',
            price:14,
            brand:'Diamond',
            rating:5,
            numReviews:10,
            description:'High quality diamond hoe. Full durability. Unenchanted.',
        },
        {
            _id:'6',
            name:'Enchanted Diamond Pickaxe',
            category: 'Pickaxe',
            image:'/images/enchanted_diamond_pickaxe.gif',
            price:100,
            brand:'Diamond',
            rating:5,
            numReviews:4,
            description:'High quality enchanted diamond pickaxe. Full durability. Efficiency V, Unbreaking III, Fortune III.',
        },
    ],
}
export default data;